version: '3.9'

services:
  web:
    build: .
    command: gunicorn erp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: oktts
      POSTGRES_USER: oktts
      POSTGRES_PASSWORD: oktts
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

volumes:
  db_data:
  static_volume:
