# Generated by Django 5.2.4 on 2025-08-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.voucher'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.paymentterm'),
        ),
    ]
