# Generated by Django 5.2.4 on 2025-08-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('investor', models.ForeignKey(limit_choices_to={'party_type': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventor_transaction', to='inventory.party')),
            ],
        ),
    ]
