# Generated by Django 5.2.4 on 2025-08-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
