# Generated by Django 5.2.4 on 2025-08-21 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_orderitem_bid_price'),
        ('sale', '0004_alter_salereturnitem_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.saleinvoice'),
        ),
    ]
