# Generated by Django 5.2.4 on 2025-08-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("setting", "0002_initial"),
        ("voucher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "supplier",
                    models.ForeignKey(
                        limit_choices_to={"party_type": "supplier"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.party",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voucher.voucher",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestorTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("investment", "Investment"),
                            ("payout", "Payout"),
                            ("profit", "Profit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "investor",
                    models.ForeignKey(
                        limit_choices_to={"party_type": "investor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.party",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investor_transactions",
                        to="purchase.purchaseinvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchaseinvoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "supplier",
                    models.ForeignKey(
                        limit_choices_to={"party_type": "supplier"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.party",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voucher.voucher",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "return_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchasereturn",
                    ),
                ),
            ],
        ),
    ]
