# Generated by Django 5.2.4 on 2025-08-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('purchase', '0001_initial'),
        ('setting', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.voucher'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.warehouse'),
        ),
        migrations.AddField(
            model_name='investortransaction',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_transactions', to='purchase.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='purchase.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'party_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.party'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.voucher'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='return_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchasereturn'),
        ),
    ]
