# Generated by Django 5.2.4 on 2025-08-03 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_employee_roles(apps, schema_editor):
    Employee = apps.get_model("hr", "Employee")
    for employee in Employee.objects.select_related("user").all():
        if employee.user_id:
            employee.role = employee.user.role
            employee.save(update_fields=["role"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        ("sale", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sale.saleinvoice"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="employee",
            field=models.ForeignKey(
                limit_choices_to={"role": "DELIVERY"},
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AddField(
            model_name="salestarget",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="salestarget",
            unique_together={("employee", "month")},
        ),
        migrations.RunPython(populate_employee_roles, migrations.RunPython.noop),
    ]
