# Generated by Django 5.2.4 on 2025-08-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.warehouse'),
        ),
        migrations.AddField(
            model_name='party',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.area'),
        ),
    ]
