
# Generated by Django 5.0.3 on 2025-08-03 19:02



import django.db.models.deletion
from django.conf import settings

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ("voucher", "0001_initial"),

    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "chart_of_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="voucher.chartofaccount",
                    ),
                ),

            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_payments",
                        to="voucher.chartofaccount",
                    ),
                ),
                (
                    "voucher",
      models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,

                        to="voucher.voucher",

                    ),
                ),
                (
                    "category",
                    models.ForeignKey(

                        on_delete=django.db.models.deletion.PROTECT,

                        to="expense.expensecategory",
                    ),
                ),
            ],
        ),

        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("voucher", "VoucherType").objects.get_or_create(
                code="EXP", defaults={"name": "Expense"}
            ),
            migrations.RunPython.noop,
        ),

    ]
