# Generated by Django 5.2.4 on 2025-08-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to='voucher.chartofaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.voucher'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='chart_of_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voucher.chartofaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense.expensecategory'),
        ),
    ]
