# Generated by Django 5.2.4 on 2025-08-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("setting", "0001_initial"),
        ("voucher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="default_purchase_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_warehouse",
                to="voucher.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="default_sales_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_warehouse",
                to="voucher.chartofaccount",
            ),
        ),
    ]
