# Generated by Django 5.2.4 on 2025-08-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="default_cash_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_warehouse",
                to="voucher.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="default_bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_warehouse",
                to="voucher.chartofaccount",
            ),
        ),
    ]
