# Generated by Django 5.2.4 on 2025-08-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="area",
            old_name="city_id",
            new_name="city",
        ),
    ]
