# Generated by Django 5.2.4 on 2025-08-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        ("inventory", "0002_initial"),
        ("setting", "0002_initial"),
        ("voucher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")], max_length=20
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"party_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.party",
                    ),
                ),
                (
                    "delivery_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="hr.employee",
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="hr.employee",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voucher.voucher",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.batch",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.saleinvoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"party_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.party",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voucher.voucher",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "return_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.salereturn",
                    ),
                ),
            ],
        ),
    ]
