# Generated by Django 5.2.4 on 2025-08-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_initial'),
        ('hr', '0002_initial'),
        ('inventory', '0002_initial'),
        ('sale', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.area'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='booking_man_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.city'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'party_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.party'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='delivery_man_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentterm'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='recoveries',
            field=models.ManyToManyField(blank=True, related_name='recovery_invoices', through='sale.RecoveryLog', to='hr.employee'),
        ),
    ]
