# Generated by Django 5.2.4 on 2025-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salereturn",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Credit", "Credit")],
                default="Cash",
                max_length=20,
            ),
        ),
    ]
