# Generated by Django 5.2.4 on 2025-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereturnitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
